### ISSUE TITLE
Generate passwords longer than 26 chars?

### ISSUE THREAD

**Issue by tripu** [tabatkins/password#3]
How difficult would it be to support generation of longer passwords, eg 32 or even 64 characters long?

Perhaps requiring also longer &ldquo;site tag&rdquo; and/or longer &ldquo;master key&rdquo; (to guarantee enough entropy)?

**Comment by tripu** [comment]
cf https://github.com/tripu/password/pull/6#issuecomment-362733629

**Comment by tabatkins** [comment]
I think it would be pretty trivial. The length is just a function argument.  That said, there doesn't seem to be any call for that sort of length. 12 characters seems to be the current minimum length, 26 seems to be vastly beyond what's going to be necessary for the long forseeable future.

**Comment by tripu** [comment]
Thank you, @tabatkins. I'll leave it at max 26 for now in my fork, too. According to what you say, if/when the need arises, I should be able to change that limit myself.

**Comment by tripu** [comment]
(Feel free to close this issue.)
